src/Entity/Property.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $swimmingpool;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sauna;

    /**
     * @ORM\Column(type="boolean")
     */
    private $wifi;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sport;

    /**
     * @ORM\Column(type="boolean")
     */
    private $helipad;

    /**
     * @ORM\Column(type="boolean")
     */
    private $terrasse;

    /**
     * @ORM\Column(type="boolean")
     */
    private $balcon;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hifi;

    /**
     * @ORM\Column(type="boolean")
     */
    private $television;

    /**
     * @ORM\Column(type="boolean")
     */
    private $plageprox;

    /**
     * @ORM\Column(type="boolean")
     */
    private $mervue;

    /**
     * @ORM\Column(type="boolean")
     */
    private $montagnevue;

    /**
     * @ORM\Column(type="boolean")
     */
    private $enville;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visavis;

    /**
     * @ORM\Column(type="boolean")
     */
    private $plageprive;

    /**
     * @ORM\Column(type="boolean")
     */
    private $pieddanseau;

    /**
     * @ORM\Column(type="boolean")
     */
    private $centreville;

    /**
     * @ORM\Column(type="boolean")
     */
    private $champetre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typepropriete;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormattedPrice() 
    {
        return number_format($this->price,0, '',' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSwimmingpool(): ?bool
    {
        return $this->swimmingpool;
    }

    public function setSwimmingpool(bool $swimmingpool): self
    {
        $this->swimmingpool = $swimmingpool;

        return $this;
    }

    public function getSauna(): ?bool
    {
        return $this->sauna;
    }

    public function setSauna(bool $sauna): self
    {
        $this->sauna = $sauna;

        return $this;
    }

    public function getWifi(): ?bool
    {
        return $this->wifi;
    }

    public function setWifi(bool $wifi): self
    {
        $this->wifi = $wifi;

        return $this;
    }

    public function getSport(): ?bool
    {
        return $this->sport;
    }

    public function setSport(bool $sport): self
    {
        $this->sport = $sport;

        return $this;
    }

    public function getHelipad(): ?bool
    {
        return $this->helipad;
    }

    public function setHelipad(bool $helipad): self
    {
        $this->helipad = $helipad;

        return $this;
    }

    public function getTerrasse(): ?bool
    {
        return $this->terrasse;
    }

    public function setTerrasse(bool $terrasse): self
    {
        $this->terrasse = $terrasse;

        return $this;
    }

    public function getBalcon(): ?bool
    {
        return $this->balcon;
    }

    public function setBalcon(bool $balcon): self
    {
        $this->balcon = $balcon;

        return $this;
    }

    public function getHifi(): ?bool
    {
        return $this->hifi;
    }

    public function setHifi(bool $hifi): self
    {
        $this->hifi = $hifi;

        return $this;
    }

    public function getTelevision(): ?bool
    {
        return $this->television;
    }

    public function setTelevision(bool $television): self
    {
        $this->television = $television;

        return $this;
    }

    public function getPlageprox(): ?bool
    {
        return $this->plageprox;
    }

    public function setPlageprox(bool $plageprox): self
    {
        $this->plageprox = $plageprox;

        return $this;
    }

    public function getMervue(): ?bool
    {
        return $this->mervue;
    }

    public function setMervue(bool $mervue): self
    {
        $this->mervue = $mervue;

        return $this;
    }

    public function getMontagnevue(): ?bool
    {
        return $this->montagnevue;
    }

    public function setMontagnevue(bool $montagnevue): self
    {
        $this->montagnevue = $montagnevue;

        return $this;
    }

    public function getEnville(): ?bool
    {
        return $this->enville;
    }

    public function setEnville(bool $enville): self
    {
        $this->enville = $enville;

        return $this;
    }

    public function getVisavis(): ?bool
    {
        return $this->visavis;
    }

    public function setVisavis(bool $visavis): self
    {
        $this->visavis = $visavis;

        return $this;
    }

    public function getPlageprive(): ?bool
    {
        return $this->plageprive;
    }

    public function setPlageprive(bool $plageprive): self
    {
        $this->plageprive = $plageprive;

        return $this;
    }

    public function getPieddanseau(): ?bool
    {
        return $this->pieddanseau;
    }

    public function setPieddanseau(bool $pieddanseau): self
    {
        $this->pieddanseau = $pieddanseau;

        return $this;
    }

    public function getCentreville(): ?bool
    {
        return $this->centreville;
    }

    public function setCentreville(bool $centreville): self
    {
        $this->centreville = $centreville;

        return $this;
    }

    public function getChampetre(): ?bool
    {
        return $this->champetre;
    }

    public function setChampetre(bool $champetre): self
    {
        $this->champetre = $champetre;

        return $this;
    }

    public function getMas(): ?bool
    {
        return $this->mas;
    }

    public function setMas(bool $mas): self
    {

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat')
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
            ->add('created_at')
            ->add('swimmingpool')
            ->add('sauna')
            ->add('wifi')
            ->add('sport')
            ->add('helipad')
            ->add('terrasse')
            ->add('balcon')
            ->add('hifi')
            ->add('television')
            ->add('plageprox')
            ->add('mervue')
            ->add('montagnevue')
            ->add('enville')
            ->add('visavis')
            ->add('plageprive')
            ->add('pieddanseau')
            ->add('centreville')
            ->add('champetre')
            ->add('typepropriete')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Form\PropertyType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/property")
 */
class PropertyController extends AbstractController
{
    /**
     * @Route("/", name="property_index", methods={"GET"})
     */
    public function index(PropertyRepository $propertyRepository): Response
    {
        return $this->render('property/index.html.twig', [
            'properties' => $propertyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="property_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('property_index');
        }

        return $this->render('property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="property_show", methods={"GET"})
     */
    public function show(Property $property): Response
    {
        return $this->render('property/show.html.twig', [
            'property' => $property,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="property_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Property $property): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('property_index');
        }

        return $this->render('property/edit.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="property_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Property $property): Response
    {
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($property);
            $entityManager->flush();
        }

        return $this->redirectToRoute('property_index');
    }
}

templates/property/_delete_form.html.twig
<form method="post" action="{{ path('property_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
    <button class="btn">Delete</button>
</form>

templates/property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Property{% endblock %}

{% block body %}
    <h1>Edit Property</h1>

    {{ include('property/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('property_index') }}">back to list</a>

    {{ include('property/_delete_form.html.twig') }}
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property index{% endblock %}

{% block body %}
    <div class="container">
        <h1>Properties</h1>
        <hr/>
        <div class="row">
            {% for property in properties %}
                <div class="col-lg-4 col-md-6">
                    <div class="card card-hover">
                        <img class="card-img-top"
                             src="https://proprietes.lefigaro.fr/indicateur/images/PDF/CMS/articles/428831262-1524579879.1.jpg"
                             alt="Card image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{ path('property_show', {id: property.id}) }}">{{ property.title }}</a>
                            </h5>
                            <p class="card-tex-tex">
                                {{ property.description }}
                            </p>
                            <p>{{ property.city }}</p>
                            <p>{{ property.address }}</p>
                            <p>{{ property.postalCode }}</p>
                            <div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.surface }}</p>
                                    </div>
                                    <div class="col-lg-2">
                                        <p>{{ property.rooms }}</p>
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-lg-3">
                                        <p>{{ property.bedrooms }}</p>
                                    </div>
                                    <div class="col-lg-3">
                                        <p>{{ property.floor }}</p>
                                    </div>
                                    <div class="col-lg-3">
                                        <p>{{ property.price }}€</p>
                                    </div>
                                    <div class="col-lg-3">
                                        <p>{{ property.heat }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.sold ? '<i class="fas fa-swimming-pool"></i>' }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.swimmingpool ? '<i class="fas fa-swimming-pool"></i>' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.sauna ? '<i class="fas fa-swimming-pool"></i>' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.wifi ? '<i class="fas fa-wifi "></i>' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.sport ? 'Yes' : 'No' }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.helipad ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.terrasse ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.balcon ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.hifi ? 'Yes' : 'No' }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.television ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.montagnevue ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.plageprox ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.mervue ? 'Yes' : 'No' }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.enville ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.visavis ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.plageprive ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.pieddanseau ? 'Yes' : 'No' }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-2">
                                        <p>{{ property.centreville ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.champetre ? 'Yes' : 'No' }}</p>
                                    </div>
                                    <div class="col-lg-1"></div>
                                    <div class="col-lg-2">
                                        <p>{{ property.typepropriete }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a class="btn btn-primary" href="{{ path('property_edit', {'id': property.id}) }}">edit</a>
                        </div>
                    </div>
                </div>
            {% else %}
                <div>
                    <p>no property found</p>
                </div>
            {% endfor %}
        </div>


        <a href="{{ path('property_new') }}">Create new</a>
    </div>

{% endblock %}

templates/property/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Property{% endblock %}

{% block body %}
    <h1>Create new Property</h1>

    {{ include('property/_form.html.twig') }}

    <a href="{{ path('property_index') }}">back to list</a>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property{% endblock %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <img>
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} pieces - {{ property.surface }} m²</h2>
                    <div class="text-primary"
                         style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }} €</div>
                    <a href="#"
                       class="btn btn-primary">Price on request</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">

        <p>
            {{ property.description | nl2br }}
        </p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }}m²</td>
                    </tr>
                    <tr>
                        <td>Pièce</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>
    </div>
    <a href="{{ path('property_index') }}">back to list</a>

    <a href="{{ path('property_edit', {'id': property.id}) }}">edit</a>

    {{ include('property/_delete_form.html.twig') }}
{% endblock %}